---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_ref: Ubuntu 14.04
      flavor_ref: SSD.30
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[openvswitch::default]
    attributes:
